django/djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

django/djangoProject/myapp/urls.py
from django.urls import path
from myapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_case, name='create_case'),
    path('<int:case_id>/', views.case_detail, name='case_detail'),
    path('<int:case_id>/update/', views.update_case, name='update_case'),
    path('create_client/', views.create_client, name='create_client'),
    path('client_list/', views.client_list, name='client_list'),
    path('client/<int:client_id>/', views.client_detail, name='client_detail'),
    path('client/<int:client_id>/update/', views.update_client, name='update_client'),
    path('area_list/', views.area_list, name='area_list'),
    path('area/<int:area_id>/', views.area_detail, name='area_detail'),


]

django/djangoProject/myapp/models.py
from django.db import models

class Area(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'myapp'

class Case(models.Model):
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

class Client(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

django/djangoProject/myapp/forms.py
from django import forms
from .models import Case, Client


class CaseForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ['area', 'title', 'description']


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'email']


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'email', 'case']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['case'].queryset = Case.objects.all()

django/djangoProject/myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Case, Client, Area
from .forms import CaseForm, ClientForm


def index(request):
    cases = Case.objects.all()
    return render(request, 'index.html', {'cases': cases})


def create_case(request):
    if request.method == 'POST':
        form = CaseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = CaseForm()
    return render(request, 'create_case.html', {'form': form})


def case_detail(request, case_id):
    case = get_object_or_404(Case, pk=case_id)
    # Получаем данные из связанных моделей
    area = case.area
    client = case.client_set.first()
    return render(request, 'case_detail.html', {'case': case, 'area': area, 'client': client})


def update_case(request, case_id):
    case = get_object_or_404(Case, pk=case_id)
    if request.method == 'POST':
        form = CaseForm(request.POST, instance=case)
        if form.is_valid():
            form.save()
            return redirect('case_detail', case_id=case.pk)
    else:
        form = CaseForm(instance=case)
    return render(request, 'update_case.html', {'form': form})


def create_client(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('client_list')
    else:
        form = ClientForm()
    return render(request, 'create_client.html', {'form': form})


def client_list(request):
    clients = Client.objects.all()
    return render(request, 'client_list.html', {'clients': clients})


def client_detail(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    return render(request, 'client_detail.html', {'client': client})


def update_client(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            return redirect('client_detail', client_id=client_id)
    else:
        form = ClientForm(instance=client)
    return render(request, 'update_client.html', {'form': form})


def area_list(request):
    areas = Area.objects.all()
    return render(request, 'area_list.html', {'areas': areas})


def area_detail(request, area_id):
    area = get_object_or_404(Area, pk=area_id)
    return render(request, 'area_detail.html', {'area': area})

django/djangoProject/myapp/templates/area_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% block title %}<title>Карточка области</title>{% endblock %}
</head>
<body>
{% block content %}
    <h1>Карточка области "{{ area.name }}"</h1>
    <h2>Список дел:</h2>
    <ul>
        {% for case in area.case_set.all %}
        <li>
            <strong>Дело: </strong>{{ case.title }}
            <ul>
                {% for client in case.client_set.all %}
                <li>{{ client.name }}</li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
{% endblock %}
</body>
</html>

django/djangoProject/myapp/templates/area_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Список областей</title>{% endblock %}
</head>
<body>
{% block content %}
    <h1>Список областей</h1>
    <ul>
        {% for area in areas %}
        <li><a href="{% url 'area_detail' area.id %}">{{ area.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}
</body>
</html>

django/djangoProject/myapp/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MyApp{% endblock %}</title>
    <style>
        /* Простой стиль для header */
        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        nav ul li {
            float: left;
        }

        nav ul li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        nav ul li a:hover {
            background-color: #111;
        }
    </style>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'area_list' %}">Области</a>
                    <ul>
                        <li><a href="{% url 'area_list' %}">Список областей</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'index' %}">Дела</a>
                    <ul>
                        <li><a href="{% url 'index' %}">Список дел</a></li>
                        <li><a href="{% url 'create_case' %}">Создать новое дело</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'client_list' %}">Клиенты</a>
                    <ul>
                        <li><a href="{% url 'client_list' %}">Список клиентов</a></li>
                        <li><a href="{% url 'create_client' %}">Добавить нового клиента</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

django/djangoProject/myapp/templates/case_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Детали дела</title>{% endblock %}
</head>
<body>
{% block content %}
    <h1>{{ case.title }}</h1>
    <p>{{ case.description }}</p>
    <a href="{% url 'update_case' case.id %}">Редактировать</a>
    <!-- Данные из связанной модели Area -->
    <h2>Область: {{ area.name }}</h2>
    <p>{{ area.description }}</p>
    <!-- Данные из связанной модели Client -->
    <h2>Клиент: {{ client.name }}</h2>
    <p>Email: {{ client.email }}</p>
{% endblock %}
</body>
</html>

django/djangoProject/myapp/templates/client_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Подробная информация о клиенте</title>{% endblock %}

</head>
<body>
{% block content %}
    <h1>Подробная информация о клиенте</h1>
    <p><strong>Имя:</strong> {{ client.name }}</p>
    <p><strong>Email:</strong> {{ client.email }}</p>
    <p><strong>Дело:</strong> {{ client.case }}</p>
    <p><strong>Область:</strong> {{ client.case.area }}</p>
    <a href="{% url 'update_client' client.id %}">Изменить</a>
{% endblock %}
</body>
</html>

django/djangoProject/myapp/templates/client_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Список клиентов</title>{% endblock %}
</head>
<body>
{% block content %}
    <h1>Список клиентов</h1>
    <ul>
        {% for client in clients %}
        <li><a href="{% url 'client_detail' client.id %}">{{ client.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}
</body>
</html>

django/djangoProject/myapp/templates/create_case.html
<!-- create_case.html -->
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
    {% block title %}<title>Добавить запись</title>{% endblock %}
</head>
<body>
{% block content %}
    <h1>Добавить запись</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}
</body>
</html>

django/djangoProject/myapp/templates/create_client.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Создание клиента</title>{% endblock %}
</head>
<body>
{% block content %}
    <h1>Создание клиента</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>
{% endblock %}
</body>
</html>

django/djangoProject/myapp/templates/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
{% block title %}<title>Главная страница</title>{% endblock %}
</head>
<body>
{% block content %}
    <h1>Список дел</h1>
    <ul>
        {% for case in cases %}
            <li><a href="{% url 'case_detail' case.id %}">{{ case.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}
</body>
</html>

django/djangoProject/myapp/templates/update_case.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Создание клиента</title>{% endblock %}
</head>
<body>
{% block content %}
    <h1>Создание клиента</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>
{% endblock %}
</body>
</html>

django/djangoProject/myapp/templates/update_client.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Редактирование информации о клиенте</title>{% endblock %}
</head>
<body>
{% block content %}
    <h1>Редактирование информации о клиенте</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}
</body>
</html>